### ISSUE TITLE
Updating database leads to mis-categorisation of user agents

### ISSUE THREAD

**Issue by writeoncereadmany** [udger/udger-java#13]
Summary: a database update put the Udger library into a state where a large proportion of desktop user agents were being mis-classified as mobile.

The database itself is fine: using it to parse user agents yields correct results. However, we saw a drastic change in behaviour which happened as the database was updated (using the https://github.com/udger/udger-updater-linux updater script), consistently across numerous hosts. 

We have not been able to replicate the issue, the majority of updates did not cause any visible issues, and all our hosts manifested the issue on the same update at the same time.

We then saw this behaviour persist after further database updates, and stop happening when we restarted the application (using the same database).

Our suspicion is that running the update script under a running application somehow led to corrupt in-memory state which mis-attributed device types. Is this something you've seen evidence of before?

**Comment by skybber** [comment]
Did you really updated DB when the clients were running ? If so, then it is not suprising that the client crashed. You should always stop the parser before you update the DB .

**Comment by kutchar** [comment]
@skybber What is the correct procedure to update the DB when using the `inMemoryEnabled=true`? 
A bit context, I have a cron that updates the DB nightly and I have a long running Java process that loads the DB into memory and processes the requests. We would like to reload the DB when the DB file is updated without restarting the Java process.

**Comment by skybber** [comment]
na tohle se budu muset podivat, jestli to vubez lze.
lada


2017-06-29 2:25 GMT+02:00 Drew Kutcharian <notifications@github.com>:

**Comment by gierlachg** [comment]
We have similar use case - reloading DB without process restart.
I believe it might be related to UdgerParser static members...

    private static WordDetector clientWordDetector;
    private static WordDetector deviceWordDetector;
    private static WordDetector osWordDetector;

    private static List<IdRegString> clientRegstringList;
    private static List<IdRegString> osRegstringList;
    private static List<IdRegString> deviceRegstringList;

Is there any specific reason for them to be static? Using parser from multiple threads is not safe anyway as far as I know.

**Comment by skybber** [comment]
The original idea was to keep expensive precalculated data in static cache, but it seems that most frequent use case is not to create Parsers frequently. I have to check  how is it with memory consumption. Anyway the thread safety is ridden by mysql driver, which is not thread safe.

**Comment by gierlachg** [comment]
Have you managed to verify memory consumption? Is it feasible to get rid of statics and make Udger reloadable?

**Comment by skybber** [comment]
Parser stores precalculated data in statics. We can store them in a some non-static context, but then we  have to change the parser API. For now, I've added static `reset` method to nullify them, but we have to extend the API by the context in the future. Would be the `reset` method enough for you?

**Comment by gierlachg** [comment]
I don't think 'reset' would be appropriate for us.
Right now we have a pool of parsers, accessed from many threads (however one at a time).
We would like to be able to create new instance of parser (with latest data) while old one could still be theoretically in use (ongoing requests etc.).

**Comment by skybber** [comment]
Are you using same file dbFileName for old/new DB ?

**Comment by gierlachg** [comment]
I'm not sure I understand what you mean.
While creating UdgerParser we pass dbFileName, yes. For different versions it is a different file though.

**Comment by skybber** [comment]
Runtime DB change support just added in v1.1.0.

**Comment by gierlachg** [comment]
Awesome. Thanks!
