### ISSUE TITLE
Parsing differenct to udger-python leading to missmatched

### ISSUE THREAD

**Issue by viblo** [udger/udger-java#14]
I have noticed that the python version of udger uses this regex `^/?(.*)/([si]*)$` to match out regexps from the database. However, the java version uses `^/?(.*?)/si$`. As you can see the java version will not match entries such as `/^Mozilla.*MSIE.*Windows.*SiteKiosk ([0-9\.]+)/s` which means it wont ever use that regexp. My guess is that the python code is correct and Java wrong.

See https://github.com/udger/udger-python/blob/master/udger/base.py#L13

**Comment by mallat** [comment]
The agreement is that the data will always only exist `..../si` .
Data corrected. Thanks for the alert.
